version: '2'
services:
  showcase-app:
    image: patrykkrawczyk/showcase
    build:
      context: ..
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://showcase-postgresql:5432/showcase
    ports:
      - 8080:8080
  showcase-postgresql:
    extends:
      file: postgresql.yml
      service: showcase-postgresql
